name: Auto Bump Node.js Version

on:
  push:
    branches:
      - master

jobs:
  bump-node-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if on master branch
      id: on-master
      run: echo ::set-output name=IS_MASTER::$(echo "${{ github.ref }}" | grep -c "refs/heads/master$")

    - name: Install Node.js using nvm
      if: steps.on-master.outputs.IS_MASTER == '1'
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Choose the desired Node.js version

    - name: Use Node.js version with nvm
      if: steps.on-master.outputs.IS_MASTER == '1'
      run: |
        # Install nvm if not already installed
        if [ ! -d ~/.nvm ]; then
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        fi
        
        # Load nvm
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

        # Install and use the specified Node.js version
        nvm install 14
        nvm use 14

    - name: Bump Node.js Version
      if: steps.on-master.outputs.IS_MASTER == '1'
      run: |
        # Run any additional Node.js version management commands you need here

    - name: Run tests or build
      if: steps.on-master.outputs.IS_MASTER == '1'
      run: |
        # Replace this with your build or test commands
        npm install
        npm run build

    # Add more steps for deployment or other actions if needed
