name: Node Version Bump

on:
  push:
    branches:
      - master

jobs:
  bump-node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/checkout@v1
      - uses: phips28/gh-action-bump-version@master
        with:
          bump-policy: 'last-commit'
          PACKAGEJSON_DIR: .
