name: Bump Node Version

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: phips28/gh-action-bump-version@v3

        with:
          bump-policy: 'ignore'
          package-file: package.json
